"""add field discount

Revision ID: 212291201df8
Revises: de97c1750f50
Create Date: 2026-05-26 09:24:18.122558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212291201df8'  # номер миграции
down_revision: Union[str, Sequence[str], None] = 'de97c1750f50'  # номер предыдущей миграции
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:  # вносит изменения в базу при алембик апгрейд
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:  # отменяет внесенные изменения в базу при алембик даунгрейд
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'discount')
    # ### end Alembic commands ###
